version: '3'

services:
  rogue-backend:
    command: yarn
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
