version: '2'

services:
  rogue-backend-dev:
    command: yarn run dev:start
    build:
      dockerfile: Dockerfile-dev
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
